// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvckuWYTytV7AKVPWj4vNvLikHRk4ikW8',
    appId: '1:552607518422:web:6a6638659b5bbafd8b0377',
    messagingSenderId: '552607518422',
    projectId: 'login-f859c',
    authDomain: 'login-f859c.firebaseapp.com',
    storageBucket: 'login-f859c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRdnYSIJV_iq_fVigW7cczQRdm-gqj01g',
    appId: '1:552607518422:android:3210d0e759a0217b8b0377',
    messagingSenderId: '552607518422',
    projectId: 'login-f859c',
    storageBucket: 'login-f859c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl4nkNImhF6P1fXGq6dblIhZEQ1VgaFdQ',
    appId: '1:552607518422:ios:95b507b9c8e1e1e08b0377',
    messagingSenderId: '552607518422',
    projectId: 'login-f859c',
    storageBucket: 'login-f859c.firebasestorage.app',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCl4nkNImhF6P1fXGq6dblIhZEQ1VgaFdQ',
    appId: '1:552607518422:ios:95b507b9c8e1e1e08b0377',
    messagingSenderId: '552607518422',
    projectId: 'login-f859c',
    storageBucket: 'login-f859c.firebasestorage.app',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvckuWYTytV7AKVPWj4vNvLikHRk4ikW8',
    appId: '1:552607518422:web:7f867aa6a13788958b0377',
    messagingSenderId: '552607518422',
    projectId: 'login-f859c',
    authDomain: 'login-f859c.firebaseapp.com',
    storageBucket: 'login-f859c.firebasestorage.app',
  );
}
